# -*- coding: utf-8 -*-
"""Niam B Song Shuffle Simulation Starter Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GdILXmKLXuODVdleGkNYlunxzFCGUeV


"""

import io
import pandas as pd

df = pd.read_csv("/Users/niambashambu/Desktop/CSCI  1300/CS LAB/Songshuffle.csv")
song_title_file = df['Name']
song_genre_file = df['Genre']

"""Y

"""

#↓↓↓ Paste Your Code Here ↓↓↓

import random
rock = 0
pop = 0
hip_hop = 0
jazz = 0
alternative = 0
electronic=0
number_songs = int(input("How many songs would you like to play?"))
song_selected = []
genre_selected = []
for i in range(number_songs):
  random_integer = random.randint(0,85)
  song = song_title_file[random_integer]
  genre = song_genre_file[random_integer]
  #print(song+" -  "+genre)
  song_selected.append(genre)
  genre_selected.append(song)
  if genre == "Rock":
    rock += 1
  elif genre == "Pop":
    pop += 1
  elif genre == "Hip Hop/R&B":
    hip_hop += 1
  elif genre == "Jazz":
    jazz += 1
  elif genre == "Alternative":
    alternative += 1
  elif genre == "Electronic":
    electronic += 1
print("")
print("The number of rock songs selected are..."+str(rock))
print("The number of pop songs selected are..."+str(pop))
print("The number of hip hop songs selected are..."+str(hip_hop))
print("The number of jazz songs selected are..."+str(jazz))
print("The number of alternative songs selected are..."+str(alternative))
print("The number of electronic songs selected are..."+str(electronic))
print("")
print("The experimental probability of rock songs selected are..."+str(rock / number_songs))
print("The experimental probability of pop songs selected are..."+str(pop / number_songs))
print("The experimental probability of hip hop songs selected are..."+str(hip_hop / number_songs))
print("The experimental probability of jazz songs selected are..."+str(jazz / number_songs))
print("The experimental probability of alternative songs selected are..."+str(alternative / number_songs))
print("The experimental probability of electronic songs selected are..."+str(electronic / number_songs))
print("")
print("The song and random genre generator has selected...")
for i in range(number_songs):
  print(str(genre_selected[i])+"   -   "+str(song_selected[i]))

